### PR TITLE
add Aldryn to dnsimple services

### PR DESCRIPTION
**Pull request by stefanfoulis**
**Do not merge. This pull request is only for our internal review, before we submit the real pull request to dnsimple.**

This adds **Divio Aldryn Cloud** as a service to [dnsimple](https://dnsimple.com/) and will be listed [here](https://dnsimple.com/domains/aldryncloud.com/applied_services)

It will end up looking roughly like this:

screen shot 2016-01-19 at 21 37 13

screen shot 2016-01-21 at 11 29 27

and the **Domain Settings** section on control.aldryn.com would be altered to have the additional **Aldryn Project Domain** section, which is always visible, even if there are no domains configured yet.

screen shot 2016-01-21 at 11 36 53

Please provide general feedback and specifically:
- are the instructions clear?
- is it clearer with the appended `.aldryn.io`, or should the field just contain the full domain name (like `mysite.us.aldryn.io`? (will users get that they don't have to paste the `.aldryn.io` part into the field?)
- do we need to add any instructions to control.aldryn.com?
- ~~There is the option to also do lookups over a webhook to our service. So we could implement it in a way, that the user only has to provide the Aldryn Project ID, or the slug. And we figure out the complete url and region on our server. But is that complexity worth it and really clearer?~~ adds no value and makes things more complicated

TODO before submitting real pull request:
- [x] remove the `_service_list.html` and `_setup.html` example docs
- [x] squash the commits

### CODE REVIEW

**Comment by stefanfoulis** [comment]
I need some more :eyes: on this please. :smile: 
@evildmp @christianbertschy @Chive @intellectronica @jmelett

**Comment by stefanfoulis** [comment]
I updated the instructions (see updated screenshot above).

**Comment by jmelett** [comment]
Looks awesome :)

Below my feedback:
- The instructions are clear IMO
- I'd let the user append the whole domain (less thinking, they can copy/paste the entire string)
- I'd just add a link on the CP which links to a tutorial ("Are you using DNSimple? Click here for instructions")

**Comment by stefanfoulis** [comment]
@jmelett ok, so only change would be to remove the appended `.aldryn.io` part of the form field?

**Comment by stefanfoulis** [comment]
I'm closing this pull request and will re-open one to the dnsimple repo.

**Pull request closed without merging**
